Update preflight for Ubuntu
ceph/cephadm-ansible pull request #40
Opened 2021-11-26 00:53 UTC by YoungjuWang

[I request PR again to clean up the commit history.]

Thank you for your checking.

Since systemd-timesyncd is running in Ubuntu by default, chrony installation and execution is excluded.

If the Ubuntu version is less than 20.10, docker is installed, and if it is 20.10 or later, podman is installed.
I haven't tested it on Debian yet, so I've only added Ubuntu. I plan to test and update playbook for Debian in the future.

2021-12-06 01:14 UTC, YoungjuWang commented
Please review the PR. Please comment if any corrections are needed.

2021-12-08 13:28 UTC, guits requested changes

2021-12-08 13:28 UTC, guits commented on cephadm-preflight.yml
> +
```suggestion

```

2021-12-08 13:28 UTC, guits commented on cephadm-preflight.yml
> +
```suggestion

```

2021-12-08 13:28 UTC, guits commented on cephadm-preflight.yml
> +                state: present
```suggestion
                state: present
```

2021-12-08 13:28 UTC, guits commented on cephadm-preflight.yml
> +            - name: configure Ceph testing repository
```suggestion
            - name: configure Ceph testing repository
```

2021-12-08 13:28 UTC, guits commented on cephadm-preflight.yml
> +                state: present
```suggestion
                state: present
```

2021-12-08 13:28 UTC, guits commented on cephadm-preflight.yml
> +
```suggestion

```

2021-12-08 13:28 UTC, guits commented on cephadm-preflight.yml
> +                    - docker
```suggestion
                    - docker
```

2021-12-08 13:28 UTC, guits commented on cephadm-preflight.yml
> +                    state: present
```suggestion
                    state: present
```

2021-12-08 13:30 UTC, guits commented
we might want to add a check for catching those nbsps 🙂

2021-12-09 04:06 UTC, YoungjuWang commented
@guits 
Thank you for your checking and changes.
Please let me know how can i resolve conflicts? Do I need to change do something?

2021-12-09 07:09 UTC, guits commented
@YoungjuWang you have to squash your commits (you should have only 1 commit) and rebase on master

2021-12-09 09:27 UTC, YoungjuWang commented
Thank you for your advice.
I squashed all commits to only 1 commit.

2021-12-15 07:05 UTC, guits commented
@YoungjuWang you need to rebase your branch

2021-12-16 04:30 UTC, YoungjuWang commented
@guits updated and squashed. please review it.

2021-12-16 08:24 UTC, guits requested changes
there are some trailing whtespaces

2021-12-16 08:36 UTC, YoungjuWang commented
@guits updated and squashed.

2021-12-16 09:28 UTC, guits commented on cephadm-preflight.yml
> +            - name: configure Ceph community repository
```suggestion
                state: present

            - name: configure Ceph community repository
```

2021-12-16 09:28 UTC, guits commented on cephadm-preflight.yml
> +        - name: install container engine
```suggestion

        - name: install container engine
```

2021-12-16 09:31 UTC, guits reviewed
just a couple of cosmetic changes, otherwise it looks good to me

2021-12-17 00:17 UTC, YoungjuWang commented
@guits It's done. review please.

2021-12-17 09:41 UTC, guits approved these changes

2021-12-23 00:22 UTC, YoungjuWang commented
Can I ask when this PR will be merged?

2021-12-23 01:38 UTC, sebastian-philipp commented
> Can I ask when this PR will be merged?

We're going to enter the Christmas holidays. Is it ok for you, if we merge this in January?

2021-12-23 01:48 UTC, YoungjuWang commented
Thank you for your answer. of course! Merry Christmas and Happy New Year.

2021-12-23 07:18 UTC, merged

2021-12-23 07:18 UTC, guits commented
> Can I ask when this PR will be merged?

sorry for the delay, thanks for your patience @YoungjuWang